### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by billdizl** [getActivity/MultiLanguages#33]
#### 问题描述

* 框架版本【必填】：8.0

* 问题描述【必填】：ANR com.hjq.language.MultiLanguages.attach (MultiLanguages.java:44)
* main (runnable):tid=1 systid=21831 
       at com.hjq.language.MultiLanguages.attach(MultiLanguages.java:44)
       at com.c.BaseApplication.attachBaseContext(BaseApplication.java:561)
       at android.app.Application.attach(Application.java:351)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:1268)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6839)
       at android.app.ActivityThread.access$1500(ActivityThread.java:252)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1999)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7877)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
jdk.internal.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:433)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
java.lang.Thread.run (Thread.java:1012)

* 复现步骤【必填】：com.hjq.language.MultiLanguages.attach (MultiLanguages.java:44)
* 启动app时就ANR

* 是否必现【必填】：否

* 出现问题的手机信息：设备
品牌：Motorola
型号：Moto G Power (2021)
屏幕方向：未知
可用 RAM： Unknown
可用磁盘空间： Unknown
操作系统
版本：Android 11
屏幕方向：未知
是否已取得 root 权限：否

* 出现问题的安卓版本：请填写出现问题的 Android 版本

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="757" alt="image" src="https://github.com/getActivity/MultiLanguages/assets/28616817/0068b4ef-0752-4eb6-abbc-8c5ce6cf5b92">

**Comment by getActivity** [comment]
还有你这个 ANR 的日志，系统会打印所有线程的日志，如果堆栈停留在这里的话也不代表是框架的问题，你怎么证明这个是框架的问题？
